services:
  api-vps:
    container_name: api-vps
    image: ghcr.io/rojolocco/api-docker-service:0.4.3
    env_file:
      - .env
    volumes:
      - api_data:/app/data
    networks:
      - internal_network
    expose:
      - 8000
    restart: unless-stopped

volumes:
  api_data:
    driver: local

networks:
  internal_network:
    driver: bridge
